apiVersion: v1
kind: Service
metadata:
   name: mongo
   labels:
     run: mongo
spec:
   ports:
   - port: 27017
     targetPort: 27017
     protocol: TCP
   selector:
     run: mongo

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: mongo
spec:
   replicas: 1
   template:
     metadata:
       labels:
         run: mongo
     spec:
       containers:
       - name: mongo
         image: mongo
         env:
         - name: MONGODB_USERNAME
           value: app
         - name: MONGODB_PASSWORD
           value: app
         ports:
         - containerPort: 27017
         volumeMounts:
         - name: mongo-volume
           mountPath: /data/db
       volumes:
       - name: mongo-volume
         persistentVolumeClaim:
           claimName: mongo-pvc