apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: auth-policy
spec:
  targets:
  - name: project
  origins:
  - jwt:
      issuer: "https://ard.au.auth0.com/"
      jwksUri: "https://ard.au.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN