apiVersion: v1
kind: Service
metadata:
   name: project
   labels:
     run: project
spec:
   ports:
   - port: 80
     targetPort: 8888
     protocol: TCP
   selector:
     run: project

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: project
spec:
   replicas: 1
   template:
     metadata:
       labels:
         run: project
     spec:
       containers:
       - name: project
         image: project:v1
         ports:
         - containerPort: 8888
       initContainers: #необходимо дождаться запуска БД.
         - name: init-mongo
           image: busybox
           command: ['sh', '-c', 'until nslookup mongo; do echo waiting for mongo; sleep 2; done;']